---

- name: Copy source dags
  copy:
    src: "{{ AIRFLOW_DAGS_SRC }}"
    dest: "{{ AIRFLOW_DAGS_DEST }}"

- name: Copy tests
  copy:
    src: "{{ AIRFLOW_TEST_SRC }}"
    dest: "{{ AIRFLOW_TEST_DEST }}"
  when: "AIRFLOW_TEST_SRC is defined and AIRFLOW_TEST_DEST is defined"

- name: Copy requirments
  copy:
    src: "{{ AIRFLOW_DAGS_REQS_SRC }}"
    dest: "{{ AIRFLOW_DAGS_REQS_DEST }}"
  when: "AIRFLOW_DAGS_REQS_SRC is defined and AIRFLOW_DAGS_REQS_DEST is defined"

- stat:
    path: "{{ AIRFLOW_DAGS_REQS_DEST }}"
  register: reqs 

- name: Install requirements
  pip:
    requirements: "{{ AIRFLOW_DAGS_REQS_DEST }}"
  when: "reqs.stat.isfile == True"
